#!/usr/bin/env -S mise tool-stub
bin = "nu"

[platforms.darwin-arm64]
url = "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-aarch64-apple-darwin.tar.gz"
checksum = "blake3:ca706abe7621dfe3093d478113d82061f9d57b874672e8ec33076c9843727f19"
size = 56186842 # 53.58 MiB

[platforms.darwin-amd64]
url = "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-x86_64-apple-darwin.tar.gz"
checksum = "blake3:a832ab8edf716d244ba3490ab82a486e7a94f6cff35b33b6ddb829e36b1b95d8"
size = 57377102 # 54.72 MiB

[platforms.linux-amd64]
url = "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-x86_64-unknown-linux-gnu.tar.gz"
checksum = "blake3:1c05e8b89e281fe6b96019893c922aa3b25c350ace141e7ee53179f6c87d0af4"
size = 62658707 # 59.76 MiB

[platforms.linux-arm64]
url = "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-aarch64-unknown-linux-gnu.tar.gz"
checksum = "blake3:dc8e2b77588bf1cfb5e4a97ea9914abaab2de77ca5e2bc8cbef1273ea8601626"
size = 61579843 # 58.73 MiB

[platforms.windows-amd64]
url = "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-x86_64-pc-windows-msvc.zip"
bin = "nu.exe"
checksum = "blake3:28739c8d2427793393ca07395c4994b5d848a9144de65819a28978342e3af71e"
size = 43717859 # 41.69 MiB
